## Rubric

Instructions: DELETE this cell before you submit via a `git push` to your repo before deadline. This cell is for your reference only and is not needed in your report. 

Scoring: Out of 10 points

- Each Developing  => -2 pts
- Each Unsatisfactory/Missing => -4 pts
  - until the score is 

If students address the detailed feedback in a future checkpoint they will earn these points back


|                  | Unsatisfactory                                                                                                                                                                                                    | Developing                                                                                                                                                                                              | Proficient                                     | Excellent                                                                                                                              |
|------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------|
| Data relevance   | Did not have data relevant to their question. Or the datasets don't work together because there is no way to line them up against each other. If there are multiple datasets, most of them have this trouble | Data was only tangentially relevant to the question or a bad proxy for the question. If there are multiple datasets, some of them may be irrelevant or can't be easily combined.                       | All data sources are relevant to the question. | Multiple data sources for each aspect of the project. It's clear how the data supports the needs of the project.                         |
| Data description | Dataset or its cleaning procedures are not described. If there are multiple datasets, most have this trouble                                                                                              | Data was not fully described. If there are multiple datasets, some of them are not fully described                                                                                                      | Data was fully described                       | The details of the data descriptions and perhaps some very basic EDA also make it clear how the data supports the needs of the project. |
| Data wrangling   | Did not obtain data. They did not clean/tidy the data they obtained.  If there are multiple datasets, most have this trouble                                                                                 | Data was partially cleaned or tidied. Perhaps you struggled to verify that the data was clean because they did not present it well. If there are multiple datasets, some have this trouble | The data is cleaned and tidied.                | The data is spotless and they used tools to visualize the data cleanliness and you were convinced at first glance                      |

# COGS 108 - Data Checkpoint

## Authors

Instructions: REPLACE the contents of this cell with your team list and their contributions. Note that this will change over the course of the checkpoints

This is a modified [CRediT taxonomy of contributions](https://credit.niso.org). For each group member please list how they contributed to this project using these terms:
> Analysis, Background research, Conceptualization, Data curation, Experimental investigation, Methodology, Project administration, Software, Visualization, Writing – original draft, Writing – review & editing

Example team list and credits:
- Alice Anderson: Conceptualization, Data curation, Methodology, Writing - original draft
- Bob Barker:  Analysis, Software, Visualization
- Charlie Chang: Project administration, Software, Writing - review & editing
- Dani Delgado: Analysis, Background research, Visualization, Writing - original draft

## Research Question

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Background and Prior Work

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Hypothesis

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Data

### Data overview

Instructions: REPLACE the contents of this cell with descriptions of your actual datasets.

For each dataset include the following information
- Dataset #1
  - Dataset Name:
  - Link to the dataset:
  - Number of observations:
  - Number of variables:
  - Description of the variables most relevant to this project
  - Descriptions of any shortcomings this dataset has with repsect to the project
- Dataset #2 (if you have more than one!)
  - same as above
- etc

Each dataset deserves either a set of bullet points as above or a few sentences if you prefer that method.

If you plan to use multiple datasets, add a few sentences about how you plan to combine these datasets.

In [1]:
# Run this code every time when you're actively developing modules in .py files.  It's not needed if you aren't making modules
#
## this code is necessary for making sure that any modules we load are updated here 
## when their source code .py files are modified

%load_ext autoreload
%autoreload 2

In [2]:
# Setup code -- this only needs to be run once after cloning the repo!
# this code downloads the data from its source to the `data/00-raw/` directory
# if the data hasn't updated you don't need to do this again!

# if you don't already have these packages (you should!) uncomment this line
# %pip install requests tqdm

import sys
sys.path.append('./modules') # this tells python where to look for modules to import

import get_data # this is where we get the function we need to download data

# replace the urls and filenames in this list with your actual datafiles
# yes you can use Google drive share links or whatever
# format is a list of dictionaries; 
# each dict has keys of 
#   'url' where the resource is located
#   'filename' for the local filename where it will be stored 
datafiles = [
    { 'url': 'https://raw.githubusercontent.com/fivethirtyeight/data/refs/heads/master/airline-safety/airline-safety.csv', 'filename':'airline-safety.csv'},
    { 'url': 'https://raw.githubusercontent.com/fivethirtyeight/data/refs/heads/master/bad-drivers/bad-drivers.csv', 'filename':'bad-drivers.csv'}
]

get_data.get_raw(datafiles,destination_directory='data/00-raw/')

Overall Download Progress:   0%|          | 0/2 [00:00<?, ?it/s]
Downloading airline-safety.csv:   0%|          | 0.00/1.23k [00:00<?, ?B/s]
Overall Download Progress:  50%|█████     | 1/2 [00:00<00:00,  3.53it/s]

Successfully downloaded: airline-safety.csv

Downloading bad-drivers.csv:   0%|          | 0.00/1.37k [00:00<?, ?B/s]
Overall Download Progress: 100%|██████████| 2/2 [00:00<00:00,  3.76it/s]

Successfully downloaded: bad-drivers.csv

### Dataset #1 

Instructions: 
1. Change the header from Dataset #1 to something more descriptive of the dataset
2. Write a few paragraphs about this dataset. Make sure to cover
   1. Describe the important metrics, what units they are in, and giv some sense of what they mean.  For example "Fasting blood glucose in units of mg glucose per deciliter of blood.  Normal values for healthy individuals range from 70 to 100 mg/dL.  Values 100-125 are prediabetic and values >125mg/dL indicate diabetes. Values <70 indicate hypoglycemia. Fasting idicates the patient hasn't eaten in the last 8 hours.  If blood glucose is >250 or <50 at any time (regardless of the time of last meal) the patient's life may be in immediate danger"
   2. If there are any major concerns with the dataset, describe them. For example "Dataset is composed of people who are serious enough about eating healthy that they voluntarily downloaded an app dedicated to tracking their eating patterns. This sample is likely biased because of that self-selection. These people own smartphones and may be healthier and may have more disposable income than the average person.  Those who voluntarily log conscientiously and for long amounts of time are also likely even more interested in health than those who download the app and only log a bit before getting tired of it"
3. Use the cell below to 
    1. load the dataset 
    2. make the dataset tidy or demonstrate that it was already tidy
    3. demonstrate the size of the dataset
    4. find out how much data is missing, where its missing, and if its missing at random or seems to have any systematic relationships in its missingness
    5. find and flag any outliers or suspicious entries
    6. clean the data or demonstrate that it was already clean.  You may choose how to deal with missingness (dropna of fillna... how='any' or 'all') and you should justify your choice in some way
    7. You will load raw data from `data/00-raw/`, you will (optionally) write intermediate stages of your work to `data/01-interim` and you will write the final fully wrangled version of your data to `data/02-processed`
4. Optionally you can also show some summary statistics for variables that you think are important to the project
5. Feel free to add more cells here if that's helpful for you

In [7]:
## YOUR CODE TO LOAD/CLEAN/TIDY/WRANGLE THE DATA GOES HERE
import pandas as pd

df_air = pd.read_csv('data/00-raw/pollution_us_2000_2016.csv')
df_air.head()

,Unnamed: 0,State Code,County Code,Site Num,Address,State,County,City,Date Local,NO2 Units,...,SO2 Units,SO2 Mean,SO2 1st Max Value,SO2 1st Max Hour,SO2 AQI,CO Units,CO Mean,CO 1st Max Value,CO 1st Max Hour,CO AQI
0,0,4,13,3002,1645 E ROOSEVELT ST-CENTRAL PHOENIX STN,Arizona,Maricopa,Phoenix,2000-01-01,Parts per billion,...,Parts per billion,3.000000,9.0,21.0,13.0,Parts per million,1.145833,4.2,21.0,NaN
1,1,4,13,3002,1645 E ROOSEVELT ST-CENTRAL PHOENIX STN,Arizona,Maricopa,Phoenix,2000-01-01,Parts per billion,...,Parts per billion,3.000000,9.0,21.0,13.0,Parts per million,0.878947,2.2,23.0,25.0
2,2,4,13,3002,1645 E ROOSEVELT ST-CENTRAL PHOENIX STN,Arizona,Maricopa,Phoenix,2000-01-01,Parts per billion,...,Parts per billion,2.975000,6.6,23.0,NaN,Parts per million,1.145833,4.2,21.0,NaN
3,3,4,13,3002,1645 E ROOSEVELT ST-CENTRAL PHOENIX STN,Arizona,Maricopa,Phoenix,2000-01-01,Parts per billion,...,Parts per billion,2.975000,6.6,23.0,NaN,Parts per million,0.878947,2.2,23.0,25.0
4,4,4,13,3002,1645 E ROOSEVELT ST-CENTRAL PHOENIX STN,Arizona,Maricopa,Phoenix,2000-01-02,Parts per billion,...,Parts per billion,1.958333,3.0,22.0,4.0,Parts per million,0.850000,1.6,23.0,NaN

In [8]:
# number of rows and columns
df_air.shape

(67043, 29)

In [9]:
# column names
df_air.columns

Index(['Unnamed: 0', 'State Code', 'County Code', 'Site Num', 'Address',
       'State', 'County', 'City', 'Date Local', 'NO2 Units', 'NO2 Mean',
       'NO2 1st Max Value', 'NO2 1st Max Hour', 'NO2 AQI', 'O3 Units',
       'O3 Mean', 'O3 1st Max Value', 'O3 1st Max Hour', 'O3 AQI', 'SO2 Units',
       'SO2 Mean', 'SO2 1st Max Value', 'SO2 1st Max Hour', 'SO2 AQI',
       'CO Units', 'CO Mean', 'CO 1st Max Value', 'CO 1st Max Hour', 'CO AQI'],
      dtype='object')

In [10]:
# information about data types
df_air.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67043 entries, 0 to 67042
Data columns (total 29 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         67043 non-null  int64
 1   State Code         67043 non-null  int64
 2   County Code        67043 non-null  int64
 3   Site Num           67043 non-null  int64
 4   Address            67043 non-null  object
 5   State              67043 non-null  object
 6   County             67043 non-null  object
 7   City               67043 non-null  object
 8   Date Local         67043 non-null  object
 9   NO2 Units          67043 non-null  object
 10  NO2 Mean           67043 non-null  float64
 11  NO2 1st Max Value  67043 non-null  float64
 12  NO2 1st Max Hour   67043 non-null  int64
 13  NO2 AQI            67043 non-null  int64
 14  O3 Units           67043 non-null  object
 15  O3 Mean            67043 non-null  float64
 16  O3 1st Max Value   67043 non-null  float64
 17  O3 1st Max Hour    67043 non-null  int64
 18  O3 AQI             67043 non-null  int64
 19  SO2 Units          67043 non-null  object
 20  SO2 Mean           67042 non-null  float64
 21  SO2 1st Max Value  67042 non-null  float64
 22  SO2 1st Max Hour   67042 non-null  float64
 23  SO2 AQI            33527 non-null  float64
 24  CO Units           67042 non-null  object
 25  CO Mean            67042 non-null  float64
 26  CO 1st Max Value   67042 non-null  float64
 27  CO 1st Max Hour    67042 non-null  float64
 28  CO AQI             33528 non-null  float64
dtypes: float64(12), int64(8), object(9)
memory usage: 14.8+ MB

In [11]:
# check for duplicate rows
df_air.duplicated().sum()

0

In [12]:
# check unique states
df_air['State'].nunique()

14

In [13]:
# check unique counties/cities
df_air['City'].nunique()

50

In [14]:
# missing values per column
df_air.isnull().sum()

Unnamed: 0               0
State Code               0
County Code              0
Site Num                 0
Address                  0
State                    0
County                   0
City                     0
Date Local               0
NO2 Units                0
NO2 Mean                 0
NO2 1st Max Value        0
NO2 1st Max Hour         0
NO2 AQI                  0
O3 Units                 0
O3 Mean                  0
O3 1st Max Value         0
O3 1st Max Hour          0
O3 AQI                   0
SO2 Units                0
SO2 Mean                 1
SO2 1st Max Value        1
SO2 1st Max Hour         1
SO2 AQI              33516
CO Units                 1
CO Mean                  1
CO 1st Max Value         1
CO 1st Max Hour          1
CO AQI               33515
dtype: int64

In [15]:
# percentage missing
(df_air.isnull().sum() / len(df_air)) * 100

Unnamed: 0            0.000000
State Code            0.000000
County Code           0.000000
Site Num              0.000000
Address               0.000000
State                 0.000000
County                0.000000
City                  0.000000
Date Local            0.000000
NO2 Units             0.000000
NO2 Mean              0.000000
NO2 1st Max Value     0.000000
NO2 1st Max Hour      0.000000
NO2 AQI               0.000000
O3 Units              0.000000
O3 Mean               0.000000
O3 1st Max Value      0.000000
O3 1st Max Hour       0.000000
O3 AQI                0.000000
SO2 Units             0.000000
SO2 Mean              0.001492
SO2 1st Max Value     0.001492
SO2 1st Max Hour      0.001492
SO2 AQI              49.991796
CO Units              0.001492
CO Mean               0.001492
CO 1st Max Value      0.001492
CO 1st Max Hour       0.001492
CO AQI               49.990305
dtype: float64

In [16]:
# keep only relevant columns
df_air = df_air[['State',
                 'County',
                 'City',
                 'Date Local',
                 'NO2 Mean',
                 'O3 Mean',
                 'SO2 Mean',
                 'CO Mean']]
# rename columns
df_air = df_air.rename(columns={
    'Date Local': 'date',
    'O3 Mean': 'ozone',
    'CO Mean': 'carbon_monoxide',
    'SO2 Mean': 'sulfur_dioxide',
    'NO2 Mean': 'nitrogen_dioxide'
})

In [17]:
df_air.describe()

       nitrogen_dioxide         ozone  sulfur_dioxide  carbon_monoxide
count      67043.000000  67043.000000    67042.000000     67042.000000
mean          17.963645      0.024039        3.021321         0.611674
std           12.463113      0.011871        3.519200         0.513417
min            0.000000      0.000000        0.000000         0.000000
25%            9.166667      0.015167        0.750000         0.279167
50%           15.666667      0.023583        2.000000         0.495833
75%           24.210526      0.031952        3.971429         0.795455
max          139.541667      0.085750       39.114286         7.508333

In [18]:
# remove rows missing ozone values
df_air = df_air.dropna(subset=['ozone'])

# remove duplicate rows
df_air = df_air.drop_duplicates()

# reset index
df_air = df_air.reset_index(drop=True)

In [19]:
df_air.shape

(62285, 8)

In [20]:
# save cleaned dataset
df_air.to_csv('data/02-processed/air_pollution_clean.csv',
              index=False)

### Dataset #2 

See instructions above for Dataset #1.  Feel free to keep adding as many more datasets as you need.  Put each new dataset in its own section just like these. 

Lastly if you do have multiple datasets, add another section where you demonstrate how you will join, align, cross-reference or whatever to combine data from the different datasets

Please note that you can always keep adding more datasets in the future if these datasets you turn in for the checkpoint aren't sufficient.  The goal here is demonstrate that you can obtain and wrangle data.  You are not tied down to only use what you turn in right now.

In [ ]:
## YOUR CODE TO LOAD/CLEAN/TIDY/WRANGLE THE DATA GOES HERE

## Ethics

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Team Expectations

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Project Timeline Proposal

Instructions: Replace this with your timeline.  **PLEASE UPDATE your Timeline!** No battle plan survives contact with the enemy, so make sure we understand how your plans have changed.  Also if you have lost points on the previous checkpoint fix them