## Rubric

Instructions: DELETE this cell before you submit via a `git push` to your repo before deadline. This cell is for your reference only and is not needed in your report. 

Scoring: Out of 10 points

- Each Developing  => -2 pts
- Each Unsatisfactory/Missing => -4 pts
  - until the score is 

If students address the detailed feedback in a future checkpoint they will earn these points back


|                  | Unsatisfactory                                                                                                                                                                                                    | Developing                                                                                                                                                                                              | Proficient                                     | Excellent                                                                                                                              |
|------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------|
| Data relevance   | Did not have data relevant to their question. Or the datasets don't work together because there is no way to line them up against each other. If there are multiple datasets, most of them have this trouble | Data was only tangentially relevant to the question or a bad proxy for the question. If there are multiple datasets, some of them may be irrelevant or can't be easily combined.                       | All data sources are relevant to the question. | Multiple data sources for each aspect of the project. It's clear how the data supports the needs of the project.                         |
| Data description | Dataset or its cleaning procedures are not described. If there are multiple datasets, most have this trouble                                                                                              | Data was not fully described. If there are multiple datasets, some of them are not fully described                                                                                                      | Data was fully described                       | The details of the data descriptions and perhaps some very basic EDA also make it clear how the data supports the needs of the project. |
| Data wrangling   | Did not obtain data. They did not clean/tidy the data they obtained.  If there are multiple datasets, most have this trouble                                                                                 | Data was partially cleaned or tidied. Perhaps you struggled to verify that the data was clean because they did not present it well. If there are multiple datasets, some have this trouble | The data is cleaned and tidied.                | The data is spotless and they used tools to visualize the data cleanliness and you were convinced at first glance                      |

# COGS 108 - Data Checkpoint

## Authors

Instructions: REPLACE the contents of this cell with your team list and their contributions. Note that this will change over the course of the checkpoints

This is a modified [CRediT taxonomy of contributions](https://credit.niso.org). For each group member please list how they contributed to this project using these terms:
> Analysis, Background research, Conceptualization, Data curation, Experimental investigation, Methodology, Project administration, Software, Visualization, Writing – original draft, Writing – review & editing

Anand Venkatesan: Hypothesis, Data, Background Research, Writing - original draft
Aviraj Singh Khanuja: Data, Hypothesis, Research Question, Writing - original draft
Martin Gama Jr: Project administration, Background Research, Ethics, Writing - review & editing
Adrian Chow: Ethics, Background research, Writing - review & editing

## Research Question

How do PM₂.₅ and ozone concentrations correlate to respiratory hospital admission rates across U.S counties and which of the two contribute more?

## Background and Prior Work

Air pollution is one of the most significant environmental threats to public health in the United States and globally. In the United States, EPA regulates six criteria pollutants under the National Ambient Air Quality Standards (NAAQS). Among these, fine particulate matter (PM2.5) and ground-level ozone (O3) have been most consistently linked to respiratory morbidity and increased hospital utilization (U.S. EPA, 2024). Despite decades of regulation under the Clean Air Act, respiratory diseases remain a leading cause of hospitalization in the United States, raising the question of how closely air quality tracks with hospital admission patterns.

PM2.5 refers to airborne particles with a diameter of 2.5 micrometers or less. Due to their extremely small size, these particles can bypass the body’s airway defenses and deposit deep in the alveoli (Xing et al., 2016). Once deposited, it triggers a cascade of harmful biological responses, like increasing the production of reactive oxygen species (ROS) in lung tissue, leading to oxidative stress, which can damage the epithelial barrier of the airways, increase susceptibility to respiratory infections, and worsen chronic conditions such as asthma and chronic obstructive pulmonary disease (COPD) (Xing et al., 2016; Li et al., 2022).

Epidemiological evidence strongly supports a positive association between PM₂.₅ exposure and respiratory hospitalizations. Zanobetti et al. (2009) found that a 10 μg/m³ increase in PM₂.₅ across 26 U.S. communities was associated with a 2.07% increase in respiratory admissions, with stronger effects in communities where PM₂.₅ contained more combustion-related components. Dominici et al. (2006) confirmed this pattern across 204 counties using Medicare data, though the association was stronger in eastern U.S. counties than western ones, suggesting the relationship may vary by region.

Ground-level ozone, unlike PM₂.₅, is not emitted directly but forms through photochemical reactions between nitrogen oxides and volatile organic compounds in sunlight (U.S. EPA, 2024). This means ozone concentrations are highly seasonal, peaking in summer and dropping in winter. This is the opposite of PM₂.₅, which tends to be elevated in winter when temperature inversions trap pollutants near the surface (Vu et al., 2022). This seasonal divergence is important because annual averages could mask seasonal spikes.

Biologically, ozone is a potent respiratory irritant. It causes bronchial inflammation, airway hyperresponsiveness, and impaired lung function upon inhalation (Lim et al., 2019). However, while ozone is linked to asthma and COPD exacerbations, its association with broader respiratory hospitalizations has been less consistent across studies than the evidence for PM₂.₅ (Zheng et al., 2021; ALA, 2025).

Most existing studies have examined PM₂.₅ and ozone individually within single cities or regions. This project compares both pollutants across U.S. counties to determine which shows a stronger association with respiratory hospitalizations.

## Hypothesis

Based on our background research, we hypothesize the following:

First, we predict that there is a significant positive association between air pollution concentrations and respiratory hospital admission rates at the county level. This prediction is grounded in the consistent epidemiological findings from multiple large-scale U.S. studies.

Second, we predict that PM2.5 will show a stronger association with respiratory hospital admission rates than ozone when examining annual county-level data. This is because of the seasonal nature of the two pollutants. Ozone formation depends on sunlight, its concentrations peak during summer and negligible during winter. PM2.5, by contrast, poses a year-round risk and is often elevated during winter. Thus, we hypothesize while examining annual county-level averages, ozone’s contribution to be lesser. Furthermore, PM2.5’s mechanism of harm involves deep alveolar deposition and inflammatory responses that can damage multiple organs. Ozone primarily affects the upper airways and bronchial passages.

## Data

### Data overview

Instructions: REPLACE the contents of this cell with descriptions of your actual datasets.

For each dataset include the following information
- Dataset #1
  - Dataset Name:
  - Link to the dataset:
  - Number of observations:
  - Number of variables:
  - Description of the variables most relevant to this project
  - Descriptions of any shortcomings this dataset has with repsect to the project
- Dataset #2 (if you have more than one!)
  - same as above
- etc

Each dataset deserves either a set of bullet points as above or a few sentences if you prefer that method.

If you plan to use multiple datasets, add a few sentences about how you plan to combine these datasets.

In [1]:
# Run this code every time when you're actively developing modules in .py files.  It's not needed if you aren't making modules
#
## this code is necessary for making sure that any modules we load are updated here 
## when their source code .py files are modified

%load_ext autoreload
%autoreload 2

In [2]:
# Setup code -- this only needs to be run once after cloning the repo!
# this code downloads the data from its source to the `data/00-raw/` directory
# if the data hasn't updated you don't need to do this again!

# if you don't already have these packages (you should!) uncomment this line
%pip install requests tqdm

import sys
sys.path.append('./modules') # this tells python where to look for modules to import

import get_data # this is where we get the function we need to download data

# replace the urls and filenames in this list with your actual datafiles
# yes you can use Google drive share links or whatever
# format is a list of dictionaries; 
# each dict has keys of 
#   'url' where the resource is located
#   'filename' for the local filename where it will be stored 
datafiles = [
    {
        "url": "https://aqs.epa.gov/aqsweb/airdata/annual_conc_by_monitor_2023.zip",
        "filename": "annual_conc_by_monitor_2023.zip"
    },
    {
        "url": "https://data.cdc.gov/api/views/swc5-untb/rows.csv?accessType=DOWNLOAD",
        "filename": "cdc_places_county_2025.csv"
    }
]

get_data.get_raw(datafiles,destination_directory='data/00-raw/')

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: requests in /opt/conda/lib/python3.11/site-packages (2.32.3)
Requirement already satisfied: tqdm in /opt/conda/lib/python3.11/site-packages (4.67.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.11/site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.11/site-packages (from requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.11/site-packages (from requests) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.11/site-packages (from requests) (2024.8.30)
Note: you may need to restart the kernel to use updated packages.

Overall Download Progress:   0%|          | 0/2 [00:00<?, ?it/s]
Downloading annual_conc_by_monitor_2023.zip:   0%|          | 0.00/4.05M [00:00<?, ?B/s]
Downloading annual_conc_by_monitor_2023.zip:   1%|          | 48.1k/4.05M [00:00<00:11, 341kB/s]
Downloading annual_conc_by_monitor_2023.zip:   3%|▎         | 136k/4.05M [00:00<00:07, 496kB/s]
Downloading annual_conc_by_monitor_2023.zip:   8%|▊         | 336k/4.05M [00:00<00:03, 984kB/s]
Downloading annual_conc_by_monitor_2023.zip:  12%|█▏        | 471k/4.05M [00:00<00:03, 1.10MB/s]
Downloading annual_conc_by_monitor_2023.zip:  18%|█▊        | 728k/4.05M [00:00<00:02, 1.36MB/s]
Downloading annual_conc_by_monitor_2023.zip:  24%|██▍       | 983k/4.05M [00:00<00:02, 1.50MB/s]
Downloading annual_conc_by_monitor_2023.zip:  31%|███       | 1.24M/4.05M [00:00<00:01, 1.58MB/s]
Downloading annual_conc_by_monitor_2023.zip:  37%|███▋      | 1.50M/4.05M [00:01<00:01, 1.64MB/s]
Downloading annual_conc_by_monitor_2023.zip:  43%|████▎     | 1.75M/4.05M [00:01<00:01, 1.67MB/s]
Downloading annual_conc_by_monitor_2023.zip:  50%|████▉     | 2.01M/4.05M [00:01<00:01, 1.70MB/s]
Downloading annual_conc_by_monitor_2023.zip:  56%|█████▌    | 2.26M/4.05M [00:01<00:01, 1.71MB/s]
Downloading annual_conc_by_monitor_2023.zip:  62%|██████▏   | 2.52M/4.05M [00:01<00:00, 1.72MB/s]
Downloading annual_conc_by_monitor_2023.zip:  69%|██████▊   | 2.78M/4.05M [00:01<00:00, 1.73MB/s]
Downloading annual_conc_by_monitor_2023.zip:  75%|███████▍  | 3.03M/4.05M [00:01<00:00, 1.73MB/s]
Downloading annual_conc_by_monitor_2023.zip:  81%|████████  | 3.29M/4.05M [00:02<00:00, 1.74MB/s]
Downloading annual_conc_by_monitor_2023.zip:  87%|████████▋ | 3.54M/4.05M [00:02<00:00, 1.74MB/s]
Downloading annual_conc_by_monitor_2023.zip:  94%|█████████▍| 3.80M/4.05M [00:02<00:00, 1.75MB/s]
Overall Download Progress:  50%|█████     | 1/2 [00:02<00:02,  2.92s/it]

Successfully downloaded: annual_conc_by_monitor_2023.zip

Downloading cdc_places_county_2025.csv: 0.00B [00:00, ?B/s]
Downloading cdc_places_county_2025.csv: 434kB [00:00, 4.10MB/s]
Downloading cdc_places_county_2025.csv: 846kB [00:00, 2.26MB/s]
Downloading cdc_places_county_2025.csv: 1.12MB [00:00, 2.01MB/s]
Downloading cdc_places_county_2025.csv: 1.37MB [00:00, 1.80MB/s]
Downloading cdc_places_county_2025.csv: 1.75MB [00:00, 1.77MB/s]
Downloading cdc_places_county_2025.csv: 2.13MB [00:01, 1.91MB/s]
Downloading cdc_places_county_2025.csv: 2.33MB [00:01, 1.83MB/s]
Downloading cdc_places_county_2025.csv: 2.52MB [00:01, 1.77MB/s]
Downloading cdc_places_county_2025.csv: 2.79MB [00:01, 1.52MB/s]
Downloading cdc_places_county_2025.csv: 3.07MB [00:01, 1.64MB/s]
Downloading cdc_places_county_2025.csv: 3.64MB [00:01, 2.07MB/s]
Downloading cdc_places_county_2025.csv: 3.92MB [00:02, 2.11MB/s]
Downloading cdc_places_county_2025.csv: 4.13MB [00:02, 1.94MB/s]
Downloading cdc_places_county_2025.csv: 4.47MB [00:02, 1.72MB/s]
Downloading cdc_places_county_2025.csv: 4.75MB [00:02, 1.85MB/s]
Downloading cdc_places_county_2025.csv: 5.11MB [00:02, 1.92MB/s]
Downloading cdc_places_county_2025.csv: 5.39MB [00:02, 1.73MB/s]
Downloading cdc_places_county_2025.csv: 5.57MB [00:03, 1.40MB/s]
Downloading cdc_places_county_2025.csv: 5.75MB [00:03, 1.38MB/s]
Downloading cdc_places_county_2025.csv: 6.12MB [00:03, 1.61MB/s]
Downloading cdc_places_county_2025.csv: 6.40MB [00:03, 1.74MB/s]
Downloading cdc_places_county_2025.csv: 6.58MB [00:03, 1.67MB/s]
Downloading cdc_places_county_2025.csv: 6.77MB [00:03, 1.44MB/s]
Downloading cdc_places_county_2025.csv: 7.04MB [00:04, 1.29MB/s]
Downloading cdc_places_county_2025.csv: 7.22MB [00:04, 1.14MB/s]
Downloading cdc_places_county_2025.csv: 7.59MB [00:04, 1.31MB/s]
Downloading cdc_places_county_2025.csv: 7.87MB [00:04, 1.50MB/s]
Downloading cdc_places_county_2025.csv: 8.23MB [00:04, 1.64MB/s]
Downloading cdc_places_county_2025.csv: 8.41MB [00:04, 1.67MB/s]
Downloading cdc_places_county_2025.csv: 8.70MB [00:05, 1.62MB/s]
Downloading cdc_places_county_2025.csv: 8.88MB [00:05, 1.48MB/s]
Downloading cdc_places_county_2025.csv: 9.08MB [00:05, 1.34MB/s]
Downloading cdc_places_county_2025.csv: 9.36MB [00:05, 1.28MB/s]
Downloading cdc_places_county_2025.csv: 9.75MB [00:06, 1.33MB/s]
Downloading cdc_places_county_2025.csv: 10.1MB [00:06, 1.64MB/s]
Downloading cdc_places_county_2025.csv: 10.4MB [00:06, 1.62MB/s]
Downloading cdc_places_county_2025.csv: 10.8MB [00:06, 1.87MB/s]
Downloading cdc_places_county_2025.csv: 11.0MB [00:06, 1.75MB/s]
Downloading cdc_places_county_2025.csv: 11.3MB [00:06, 1.52MB/s]
Downloading cdc_places_county_2025.csv: 11.5MB [00:07, 1.43MB/s]
Downloading cdc_places_county_2025.csv: 11.7MB [00:07, 1.20MB/s]
Downloading cdc_places_county_2025.csv: 12.1MB [00:07, 1.36MB/s]
Downloading cdc_places_county_2025.csv: 12.3MB [00:07, 1.27MB/s]
Downloading cdc_places_county_2025.csv: 12.5MB [00:07, 1.24MB/s]
Downloading cdc_places_county_2025.csv: 12.8MB [00:08, 1.24MB/s]
Downloading cdc_places_county_2025.csv: 13.0MB [00:08, 1.21MB/s]
Downloading cdc_places_county_2025.csv: 13.2MB [00:08, 1.32MB/s]
Downloading cdc_places_county_2025.csv: 13.6MB [00:08, 1.40MB/s]
Downloading cdc_places_county_2025.csv: 13.9MB [00:08, 1.32MB/s]
Downloading cdc_places_county_2025.csv: 14.1MB [00:09, 1.40MB/s]
Downloading cdc_places_county_2025.csv: 14.2MB [00:09, 1.33MB/s]
Downloading cdc_places_county_2025.csv: 14.4MB [00:09, 1.43MB/s]
Downloading cdc_places_county_2025.csv: 15.1MB [00:09, 1.74MB/s]
Downloading cdc_places_county_2025.csv: 15.3MB [00:09, 1.59MB/s]
Downloading cdc_places_county_2025.csv: 15.5MB [00:09, 1.46MB/s]
Downloading cdc_places_county_2025.csv: 15.7MB [00:10, 1.12MB/s]
Downloading cdc_places_county_2025.csv: 15.8MB [00:10, 1.05MB/s]
Downloading cdc_places_county_2025.csv: 16.2MB [00:10, 1.47MB/s]
Downloading cdc_places_county_2025.csv: 16.8MB [00:10, 2.34MB/s]
Downloading cdc_places_county_2025.csv: 17.5MB [00:10, 2.56MB/s]
Downloading cdc_places_county_2025.csv: 17.8MB [00:11, 2.30MB/s]
Downloading cdc_places_county_2025.csv: 18.1MB [00:11, 2.13MB/s]
Downloading cdc_places_county_2025.csv: 18.3MB [00:11, 1.98MB/s]
Downloading cdc_places_county_2025.csv: 18.5MB [00:11, 1.79MB/s]
Downloading cdc_places_county_2025.csv: 19.0MB [00:11, 2.33MB/s]
Downloading cdc_places_county_2025.csv: 19.6MB [00:11, 3.06MB/s]
Downloading cdc_places_county_2025.csv: 20.0MB [00:11, 2.61MB/s]
Downloading cdc_places_county_2025.csv: 20.4MB [00:12, 2.62MB/s]
Downloading cdc_places_county_2025.csv: 20.7MB [00:12, 2.36MB/s]
Downloading cdc_places_county_2025.csv: 21.0MB [00:12, 2.10MB/s]
Downloading cdc_places_county_2025.csv: 21.2MB [00:12, 2.14MB/s]
Downloading cdc_places_county_2025.csv: 21.5MB [00:12, 1.90MB/s]
Downloading cdc_places_county_2025.csv: 21.7MB [00:12, 1.74MB/s]
Downloading cdc_places_county_2025.csv: 21.9MB [00:13, 1.27MB/s]
Downloading cdc_places_county_2025.csv: 22.2MB [00:13, 1.29MB/s]
Downloading cdc_places_county_2025.csv: 22.3MB [00:13, 1.27MB/s]
Downloading cdc_places_county_2025.csv: 22.5MB [00:13, 1.31MB/s]
Downloading cdc_places_county_2025.csv: 23.0MB [00:13, 1.96MB/s]
Downloading cdc_places_county_2025.csv: 23.7MB [00:13, 2.89MB/s]
Downloading cdc_places_county_2025.csv: 24.4MB [00:14, 3.89MB/s]
Downloading cdc_places_county_2025.csv: 24.9MB [00:14, 2.97MB/s]
Downloading cdc_places_county_2025.csv: 25.3MB [00:14, 1.84MB/s]
Downloading cdc_places_county_2025.csv: 25.5MB [00:14, 1.97MB/s]
Downloading cdc_places_county_2025.csv: 25.8MB [00:15, 1.45MB/s]
Downloading cdc_places_county_2025.csv: 26.1MB [00:15, 1.31MB/s]
Downloading cdc_places_county_2025.csv: 26.3MB [00:15, 1.13MB/s]
Downloading cdc_places_county_2025.csv: 26.5MB [00:15, 1.07MB/s]
Downloading cdc_places_county_2025.csv: 26.6MB [00:16, 1.01MB/s]
Downloading cdc_places_county_2025.csv: 26.8MB [00:16, 943kB/s]
Downloading cdc_places_county_2025.csv: 26.9MB [00:16, 823kB/s]
Downloading cdc_places_county_2025.csv: 27.1MB [00:16, 838kB/s]
Downloading cdc_places_county_2025.csv: 27.3MB [00:17, 874kB/s]
Downloading cdc_places_county_2025.csv: 27.5MB [00:17, 854kB/s]
Downloading cdc_places_county_2025.csv: 27.7MB [00:17, 973kB/s]
Downloading cdc_places_county_2025.csv: 28.2MB [00:17, 1.64MB/s]
Downloading cdc_places_county_2025.csv: 28.7MB [00:17, 1.77MB/s]
Downloading cdc_places_county_2025.csv: 28.9MB [00:17, 1.67MB/s]
Downloading cdc_places_county_2025.csv: 29.1MB [00:18, 1.60MB/s]
Downloading cdc_places_county_2025.csv: 29.2MB [00:18, 1.40MB/s]
Downloading cdc_places_county_2025.csv: 29.4MB [00:18, 1.35MB/s]
Downloading cdc_places_county_2025.csv: 29.6MB [00:18, 1.16MB/s]
Downloading cdc_places_county_2025.csv: 29.7MB [00:18, 1.16MB/s]
Downloading cdc_places_county_2025.csv: 30.3MB [00:18, 2.08MB/s]
Downloading cdc_places_county_2025.csv: 30.6MB [00:18, 2.03MB/s]
Downloading cdc_places_county_2025.csv: 30.8MB [00:19, 1.84MB/s]
Downloading cdc_places_county_2025.csv: 31.0MB [00:19, 1.73MB/s]
Downloading cdc_places_county_2025.csv: 31.2MB [00:19, 1.68MB/s]
Downloading cdc_places_county_2025.csv: 31.4MB [00:19, 1.67MB/s]
Downloading cdc_places_county_2025.csv: 31.9MB [00:19, 2.35MB/s]
Downloading cdc_places_county_2025.csv: 32.6MB [00:19, 3.17MB/s]
Downloading cdc_places_county_2025.csv: 33.0MB [00:20, 2.05MB/s]
Downloading cdc_places_county_2025.csv: 33.2MB [00:20, 2.06MB/s]
Downloading cdc_places_county_2025.csv: 33.5MB [00:20, 1.90MB/s]
Downloading cdc_places_county_2025.csv: 33.7MB [00:20, 1.50MB/s]
Downloading cdc_places_county_2025.csv: 33.8MB [00:20, 1.43MB/s]
Downloading cdc_places_county_2025.csv: 34.0MB [00:20, 1.27MB/s]
Downloading cdc_places_county_2025.csv: 34.3MB [00:21, 1.24MB/s]
Downloading cdc_places_county_2025.csv: 34.6MB [00:21, 1.51MB/s]
Downloading cdc_places_county_2025.csv: 34.8MB [00:21, 1.51MB/s]
Downloading cdc_places_county_2025.csv: 35.0MB [00:21, 1.45MB/s]
Downloading cdc_places_county_2025.csv: 35.2MB [00:21, 1.45MB/s]
Downloading cdc_places_county_2025.csv: 35.4MB [00:21, 1.15MB/s]
Downloading cdc_places_county_2025.csv: 35.5MB [00:22, 1.02MB/s]
Downloading cdc_places_county_2025.csv: 35.7MB [00:22, 1.02MB/s]
Downloading cdc_places_county_2025.csv: 35.9MB [00:22, 1.06MB/s]
Downloading cdc_places_county_2025.csv: 36.1MB [00:22, 1.05MB/s]
Downloading cdc_places_county_2025.csv: 36.7MB [00:22, 1.97MB/s]
Downloading cdc_places_county_2025.csv: 37.0MB [00:22, 1.89MB/s]
Downloading cdc_places_county_2025.csv: 37.4MB [00:23, 2.08MB/s]
Downloading cdc_places_county_2025.csv: 37.6MB [00:23, 1.95MB/s]
Downloading cdc_places_county_2025.csv: 37.8MB [00:23, 1.87MB/s]
Downloading cdc_places_county_2025.csv: 38.1MB [00:23, 1.69MB/s]
Downloading cdc_places_county_2025.csv: 38.2MB [00:23, 1.62MB/s]
Downloading cdc_places_county_2025.csv: 38.4MB [00:23, 1.59MB/s]
Downloading cdc_places_county_2025.csv: 38.6MB [00:23, 1.45MB/s]
Downloading cdc_places_county_2025.csv: 38.7MB [00:24, 1.32MB/s]
Downloading cdc_places_county_2025.csv: 39.3MB [00:24, 1.71MB/s]
Downloading cdc_places_county_2025.csv: 39.4MB [00:24, 1.68MB/s]
Downloading cdc_places_county_2025.csv: 39.6MB [00:24, 1.21MB/s]
Downloading cdc_places_county_2025.csv: 39.7MB [00:24, 1.05MB/s]
Downloading cdc_places_county_2025.csv: 39.9MB [00:25, 1.04MB/s]
Downloading cdc_places_county_2025.csv: 40.0MB [00:25, 902kB/s]
Downloading cdc_places_county_2025.csv: 40.2MB [00:25, 818kB/s]
Downloading cdc_places_county_2025.csv: 40.4MB [00:25, 901kB/s]
Downloading cdc_places_county_2025.csv: 40.5MB [00:25, 853kB/s]
Downloading cdc_places_county_2025.csv: 40.7MB [00:26, 922kB/s]
Downloading cdc_places_county_2025.csv: 40.8MB [00:26, 736kB/s]
Downloading cdc_places_county_2025.csv: 41.2MB [00:26, 1.21MB/s]
Downloading cdc_places_county_2025.csv: 41.6MB [00:26, 1.72MB/s]
Downloading cdc_places_county_2025.csv: 41.9MB [00:26, 1.41MB/s]
Downloading cdc_places_county_2025.csv: 42.0MB [00:27, 1.09MB/s]
Downloading cdc_places_county_2025.csv: 42.3MB [00:27, 1.06MB/s]
Downloading cdc_places_county_2025.csv: 42.6MB [00:27, 1.35MB/s]
Downloading cdc_places_county_2025.csv: 42.9MB [00:27, 1.58MB/s]
Downloading cdc_places_county_2025.csv: 43.5MB [00:27, 1.81MB/s]
Downloading cdc_places_county_2025.csv: 43.7MB [00:28, 1.66MB/s]
Downloading cdc_places_county_2025.csv: 43.8MB [00:28, 1.60MB/s]
Downloading cdc_places_county_2025.csv: 44.0MB [00:28, 1.40MB/s]
Downloading cdc_places_county_2025.csv: 44.1MB [00:28, 1.37MB/s]
Downloading cdc_places_county_2025.csv: 44.3MB [00:28, 1.33MB/s]
Downloading cdc_places_county_2025.csv: 44.5MB [00:28, 1.29MB/s]
Downloading cdc_places_county_2025.csv: 44.7MB [00:28, 1.22MB/s]
Downloading cdc_places_county_2025.csv: 44.9MB [00:29, 1.20MB/s]
Downloading cdc_places_county_2025.csv: 45.1MB [00:29, 1.30MB/s]
Downloading cdc_places_county_2025.csv: 45.4MB [00:29, 1.51MB/s]
Downloading cdc_places_county_2025.csv: 45.9MB [00:29, 2.28MB/s]
Downloading cdc_places_county_2025.csv: 46.4MB [00:29, 2.41MB/s]
Downloading cdc_places_county_2025.csv: 46.6MB [00:29, 2.34MB/s]
Downloading cdc_places_county_2025.csv: 46.9MB [00:30, 1.56MB/s]
Downloading cdc_places_county_2025.csv: 47.1MB [00:30, 1.44MB/s]
Downloading cdc_places_county_2025.csv: 47.2MB [00:30, 1.39MB/s]
Downloading cdc_places_county_2025.csv: 47.4MB [00:30, 1.33MB/s]
Downloading cdc_places_county_2025.csv: 47.6MB [00:30, 1.27MB/s]
Downloading cdc_places_county_2025.csv: 47.7MB [00:30, 1.18MB/s]
Downloading cdc_places_county_2025.csv: 48.1MB [00:30, 1.59MB/s]
Downloading cdc_places_county_2025.csv: 48.3MB [00:31, 1.54MB/s]
Downloading cdc_places_county_2025.csv: 48.4MB [00:31, 1.54MB/s]
Downloading cdc_places_county_2025.csv: 48.6MB [00:31, 1.31MB/s]
Downloading cdc_places_county_2025.csv: 48.7MB [00:31, 1.16MB/s]
Downloading cdc_places_county_2025.csv: 48.9MB [00:31, 1.28MB/s]
Downloading cdc_places_county_2025.csv: 49.1MB [00:31, 1.20MB/s]
Downloading cdc_places_county_2025.csv: 49.2MB [00:31, 1.21MB/s]
Downloading cdc_places_county_2025.csv: 49.6MB [00:32, 1.20MB/s]
Downloading cdc_places_county_2025.csv: 50.0MB [00:32, 1.76MB/s]
Downloading cdc_places_county_2025.csv: 50.2MB [00:32, 1.31MB/s]
Downloading cdc_places_county_2025.csv: 50.4MB [00:32, 1.04MB/s]
Downloading cdc_places_county_2025.csv: 50.6MB [00:33, 817kB/s]
Downloading cdc_places_county_2025.csv: 50.8MB [00:33, 878kB/s]
Downloading cdc_places_county_2025.csv: 50.9MB [00:33, 803kB/s]
Downloading cdc_places_county_2025.csv: 51.1MB [00:33, 918kB/s]
Downloading cdc_places_county_2025.csv: 51.3MB [00:34, 1.03MB/s]
Downloading cdc_places_county_2025.csv: 51.5MB [00:34, 1.20MB/s]
Downloading cdc_places_county_2025.csv: 52.0MB [00:34, 1.83MB/s]
Downloading cdc_places_county_2025.csv: 52.4MB [00:34, 1.82MB/s]
Downloading cdc_places_county_2025.csv: 52.6MB [00:34, 1.55MB/s]
Downloading cdc_places_county_2025.csv: 52.8MB [00:34, 1.36MB/s]
Downloading cdc_places_county_2025.csv: 53.0MB [00:35, 1.29MB/s]
Downloading cdc_places_county_2025.csv: 53.1MB [00:35, 1.30MB/s]
Overall Download Progress: 100%|██████████| 2/2 [00:43<00:00, 21.91s/it]

Successfully downloaded: cdc_places_county_2025.csv

### Dataset #1 

Instructions: 
1. Change the header from Dataset #1 to something more descriptive of the dataset
2. Write a few paragraphs about this dataset. Make sure to cover
   1. Describe the important metrics, what units they are in, and giv some sense of what they mean.  For example "Fasting blood glucose in units of mg glucose per deciliter of blood.  Normal values for healthy individuals range from 70 to 100 mg/dL.  Values 100-125 are prediabetic and values >125mg/dL indicate diabetes. Values <70 indicate hypoglycemia. Fasting idicates the patient hasn't eaten in the last 8 hours.  If blood glucose is >250 or <50 at any time (regardless of the time of last meal) the patient's life may be in immediate danger"
   2. If there are any major concerns with the dataset, describe them. For example "Dataset is composed of people who are serious enough about eating healthy that they voluntarily downloaded an app dedicated to tracking their eating patterns. This sample is likely biased because of that self-selection. These people own smartphones and may be healthier and may have more disposable income than the average person.  Those who voluntarily log conscientiously and for long amounts of time are also likely even more interested in health than those who download the app and only log a bit before getting tired of it"
3. Use the cell below to 
    1. load the dataset 
    2. make the dataset tidy or demonstrate that it was already tidy
    3. demonstrate the size of the dataset
    4. find out how much data is missing, where its missing, and if its missing at random or seems to have any systematic relationships in its missingness
    5. find and flag any outliers or suspicious entries
    6. clean the data or demonstrate that it was already clean.  You may choose how to deal with missingness (dropna of fillna... how='any' or 'all') and you should justify your choice in some way
    7. You will load raw data from `data/00-raw/`, you will (optionally) write intermediate stages of your work to `data/01-interim` and you will write the final fully wrangled version of your data to `data/02-processed`
4. Optionally you can also show some summary statistics for variables that you think are important to the project
5. Feel free to add more cells here if that's helpful for you

In [21]:
## YOUR CODE TO LOAD/CLEAN/TIDY/WRANGLE THE DATA GOES HERE
import pandas as pd
import os
import zipfile

zip_path = "data/00-raw/annual_conc_by_monitor_2023.zip"

with zipfile.ZipFile(zip_path) as zipped_file:
    with zipped_file.open("annual_conc_by_monitor_2023/annual_conc_by_monitor_2023.csv") as file:
        air_quality = pd.read_csv(file)

air_quality.head()

,State Code,County Code,Site Num,Parameter Code,POC,Latitude,Longitude,Datum,Parameter Name,Sample Duration,...,75th Percentile,50th Percentile,10th Percentile,Local Site Name,Address,State Name,County Name,City Name,CBSA Name,Date of Last Change
0,1,3,10,44201,1,30.497478,-87.880258,NAD83,Ozone,1 HOUR,...,0.055,0.049,0.033,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE...",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",5/24/2024
1,1,3,10,44201,1,30.497478,-87.880258,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,...,0.051,0.044,0.028,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE...",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",5/24/2024
2,1,3,10,44201,1,30.497478,-87.880258,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,...,0.051,0.044,0.028,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE...",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",5/24/2024
3,1,3,10,44201,1,30.497478,-87.880258,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,...,0.051,0.045,0.028,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE...",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",5/24/2024
4,1,3,10,88101,3,30.497478,-87.880258,NAD83,PM2.5 - Local Conditions,1 HOUR,...,10.600,7.000,1.400,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE...",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",8/6/2024

In [22]:
air_quality.shape

(82378, 55)

In [23]:
air_quality.columns

Index(['State Code', 'County Code', 'Site Num', 'Parameter Code', 'POC',
       'Latitude', 'Longitude', 'Datum', 'Parameter Name', 'Sample Duration',
       'Pollutant Standard', 'Metric Used', 'Method Name', 'Year',
       'Units of Measure', 'Event Type', 'Observation Count',
       'Observation Percent', 'Completeness Indicator', 'Valid Day Count',
       'Required Day Count', 'Exceptional Data Count', 'Null Data Count',
       'Primary Exceedance Count', 'Secondary Exceedance Count',
       'Certification Indicator', 'Num Obs Below MDL', 'Arithmetic Mean',
       'Arithmetic Standard Dev', '1st Max Value', '1st Max DateTime',
       '2nd Max Value', '2nd Max DateTime', '3rd Max Value',
       '3rd Max DateTime', '4th Max Value', '4th Max DateTime',
       '1st Max Non Overlapping Value', '1st NO Max DateTime',
       '2nd Max Non Overlapping Value', '2nd NO Max DateTime',
       '99th Percentile', '98th Percentile', '95th Percentile',
       '90th Percentile', '75th Percentile', '50th Percentile',
       '10th Percentile', 'Local Site Name', 'Address', 'State Name',
       'County Name', 'City Name', 'CBSA Name', 'Date of Last Change'],
      dtype='object')

In [24]:
air_quality["Parameter Name"].value_counts().head(20)

Parameter Name
PM2.5 - Local Conditions                  26434
Ozone                                      5892
Sulfur dioxide                             2268
PM10 Total 0-10um STP                      1484
Outdoor Temperature                        1084
Nitrogen dioxide (NO2)                      914
Wind Direction - Resultant                  712
Wind Speed - Resultant                      707
Acceptable PM2.5 AQI & Speciation Mass      683
Wind Speed - Scalar                         567
Carbon monoxide                             501
PM10 - LC                                   482
Average Ambient Temperature                 477
Average Ambient Pressure                    477
Std Dev Hz Wind Direction                   451
Nitric oxide (NO)                           448
Relative Humidity                           438
Wind Direction - Scalar                     369
Oxides of nitrogen (NOx)                    363
PM10-2.5 - Local Conditions                 314
Name: count, dtype: int64

In [25]:
target_pollutants = ["PM2.5 - Local Conditions", "Ozone"]

air_quality_pollutants = air_quality[
    air_quality["Parameter Name"].isin(target_pollutants)
].copy()

air_quality_pollutants["Parameter Name"].value_counts()

Parameter Name
PM2.5 - Local Conditions    26434
Ozone                        5892
Name: count, dtype: int64

In [26]:
air_quality_pollutants["State Code"] = air_quality_pollutants["State Code"].astype(str).str.zfill(2)
air_quality_pollutants["County Code"] = air_quality_pollutants["County Code"].astype(str).str.zfill(3)

air_quality_pollutants["county_fips"] = (
    air_quality_pollutants["State Code"] + air_quality_pollutants["County Code"]
)

air_quality_pollutants.head()

,State Code,County Code,Site Num,Parameter Code,POC,Latitude,Longitude,Datum,Parameter Name,Sample Duration,...,50th Percentile,10th Percentile,Local Site Name,Address,State Name,County Name,City Name,CBSA Name,Date of Last Change,county_fips
0,01,003,10,44201,1,30.497478,-87.880258,NAD83,Ozone,1 HOUR,...,0.049,0.033,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE...",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",5/24/2024,01003
1,01,003,10,44201,1,30.497478,-87.880258,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,...,0.044,0.028,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE...",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",5/24/2024,01003
2,01,003,10,44201,1,30.497478,-87.880258,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,...,0.044,0.028,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE...",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",5/24/2024,01003
3,01,003,10,44201,1,30.497478,-87.880258,NAD83,Ozone,8-HR RUN AVG BEGIN HOUR,...,0.045,0.028,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE...",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",5/24/2024,01003
4,01,003,10,88101,3,30.497478,-87.880258,NAD83,PM2.5 - Local Conditions,1 HOUR,...,7.000,1.400,"FAIRHOPE, Alabama","FAIRHOPE HIGH SCHOOL, 1 PIRATE DRIVE, FAIRHOPE...",Alabama,Baldwin,Fairhope,"Daphne-Fairhope-Foley, AL",8/6/2024,01003

In [27]:
air_quality_clean = air_quality_pollutants[
    [
        "county_fips",
        "State Name",
        "County Name",
        "Year",
        "Parameter Name",
        "Sample Duration",
        "Units of Measure",
        "Arithmetic Mean",
        "Observation Count",
        "Observation Percent",
        "Latitude",
        "Longitude"
    ]
].copy()

air_quality_clean.head()

,county_fips,State Name,County Name,Year,Parameter Name,Sample Duration,Units of Measure,Arithmetic Mean,Observation Count,Observation Percent,Latitude,Longitude
0,01003,Alabama,Baldwin,2023,Ozone,1 HOUR,Parts per million,0.047836,5148,92,30.497478,-87.880258
1,01003,Alabama,Baldwin,2023,Ozone,8-HR RUN AVG BEGIN HOUR,Parts per million,0.043288,5345,91,30.497478,-87.880258
2,01003,Alabama,Baldwin,2023,Ozone,8-HR RUN AVG BEGIN HOUR,Parts per million,0.043288,5345,91,30.497478,-87.880258
3,01003,Alabama,Baldwin,2023,Ozone,8-HR RUN AVG BEGIN HOUR,Parts per million,0.043255,3789,88,30.497478,-87.880258
4,01003,Alabama,Baldwin,2023,PM2.5 - Local Conditions,1 HOUR,Micrograms/cubic meter (LC),7.690417,8150,93,30.497478,-87.880258

In [28]:
air_quality_clean.isna().sum()

county_fips            0
State Name             0
County Name            0
Year                   0
Parameter Name         0
Sample Duration        0
Units of Measure       0
Arithmetic Mean        4
Observation Count      0
Observation Percent    0
Latitude               0
Longitude              0
dtype: int64

In [29]:
air_quality_clean[["Arithmetic Mean", "Observation Count", "Observation Percent"]].describe()

       Arithmetic Mean  Observation Count  Observation Percent
count     32322.000000       32326.000000         32326.000000
mean          6.954423        1857.596424            87.179484
std           3.869509        2972.123890            19.944873
min           0.014442           1.000000             0.000000
25%           5.213605         138.000000            87.000000
50%           7.997778         321.000000            97.000000
75%           9.575691        2218.750000            99.000000
max          28.664706        8759.000000           100.000000

In [30]:
air_quality_clean.sort_values("Arithmetic Mean").head()

,county_fips,State Name,County Name,Year,Parameter Name,Sample Duration,Units of Measure,Arithmetic Mean,Observation Count,Observation Percent,Latitude,Longitude
49194,35045,New Mexico,San Juan,2023,Ozone,8-HR RUN AVG BEGIN HOUR,Parts per million,0.014442,5794,66,36.807100,-108.695230
49195,35045,New Mexico,San Juan,2023,Ozone,8-HR RUN AVG BEGIN HOUR,Parts per million,0.014442,5794,66,36.807100,-108.695230
49196,35045,New Mexico,San Juan,2023,Ozone,8-HR RUN AVG BEGIN HOUR,Parts per million,0.014460,4114,65,36.807100,-108.695230
49193,35045,New Mexico,San Juan,2023,Ozone,1 HOUR,Parts per million,0.016542,5844,66,36.807100,-108.695230
82172,72021,Puerto Rico,Bayamon,2023,Ozone,8-HR RUN AVG BEGIN HOUR,Parts per million,0.021471,584,9,18.420089,-66.150615

In [31]:
air_quality_clean.sort_values("Arithmetic Mean", ascending=False).head()

,county_fips,State Name,County Name,Year,Parameter Name,Sample Duration,Units of Measure,Arithmetic Mean,Observation Count,Observation Percent,Latitude,Longitude
58371,39153,Ohio,Summit,2023,PM2.5 - Local Conditions,24-HR BLK AVG,Micrograms/cubic meter (LC),28.664706,17,5,41.063526,-81.468956
58374,39153,Ohio,Summit,2023,PM2.5 - Local Conditions,24-HR BLK AVG,Micrograms/cubic meter (LC),28.664706,17,5,41.063526,-81.468956
58373,39153,Ohio,Summit,2023,PM2.5 - Local Conditions,24-HR BLK AVG,Micrograms/cubic meter (LC),28.664706,17,5,41.063526,-81.468956
58372,39153,Ohio,Summit,2023,PM2.5 - Local Conditions,24-HR BLK AVG,Micrograms/cubic meter (LC),28.664706,17,5,41.063526,-81.468956
58370,39153,Ohio,Summit,2023,PM2.5 - Local Conditions,24-HR BLK AVG,Micrograms/cubic meter (LC),28.664706,17,5,41.063526,-81.468956

In [32]:
os.makedirs("data/01-interim", exist_ok=True)

air_quality_clean.to_csv(
    "data/01-interim/epa_air_quality_pm25_ozone_2023.csv",
    index=False
)

### Dataset #2 

See instructions above for Dataset #1.  Feel free to keep adding as many more datasets as you need.  Put each new dataset in its own section just like these. 

Lastly if you do have multiple datasets, add another section where you demonstrate how you will join, align, cross-reference or whatever to combine data from the different datasets

Please note that you can always keep adding more datasets in the future if these datasets you turn in for the checkpoint aren't sufficient.  The goal here is demonstrate that you can obtain and wrangle data.  You are not tied down to only use what you turn in right now.

In [38]:
## YOUR CODE TO LOAD/CLEAN/TIDY/WRANGLE THE DATA GOES HERE
places = pd.read_csv(
    "data/00-raw/cdc_places_county_2025.csv",
    dtype={"LocationID": str},
    low_memory=False
)

places["LocationID"] = places["LocationID"].str.zfill(5)

places.head()

,Year,StateAbbr,StateDesc,LocationName,DataSource,Category,Measure,Data_Value_Unit,Data_Value_Type,Data_Value,...,Low_Confidence_Limit,High_Confidence_Limit,TotalPopulation,TotalPop18plus,LocationID,CategoryID,MeasureId,DataValueTypeID,Short_Question_Text,Geolocation
0,2023,AR,Arkansas,Drew,BRFSS,Health Outcomes,Arthritis among adults,%,Crude prevalence,29.9,...,26.6,33.3,16945,13230,05043,HLTHOUT,ARTHRITIS,CrdPrv,Arthritis,POINT (-91.7196579038053 33.5894113647675)
1,2023,AR,Arkansas,Fulton,BRFSS,Health Outcomes,Current asthma among adults,%,Crude prevalence,10.6,...,9.2,11.9,12421,9795,05049,HLTHOUT,CASTHMA,CrdPrv,Current Asthma,POINT (-91.817888079321 36.3816206347765)
2,2023,AR,Arkansas,Howard,BRFSS,Health Outcomes,Arthritis among adults,%,Crude prevalence,31.2,...,27.7,34.8,12533,9311,05061,HLTHOUT,ARTHRITIS,CrdPrv,Arthritis,POINT (-93.9938053308515 34.0889044688856)
3,2023,AR,Arkansas,Miller,BRFSS,Health Outcomes,Stroke among adults,%,Crude prevalence,4.7,...,4.2,5.3,42415,32396,05091,HLTHOUT,STROKE,CrdPrv,Stroke,POINT (-93.8924281761086 33.3123156126392)
4,2023,AR,Arkansas,Ouachita,BRFSS,Disability,Any disability among adults,%,Crude prevalence,42.8,...,37.9,47.8,21793,16948,05103,DISABLT,DISABILITY,CrdPrv,Any Disability,POINT (-92.882040791321 33.593253927504)

In [39]:
places.shape

(229298, 22)

In [40]:
places.columns

Index(['Year', 'StateAbbr', 'StateDesc', 'LocationName', 'DataSource',
       'Category', 'Measure', 'Data_Value_Unit', 'Data_Value_Type',
       'Data_Value', 'Data_Value_Footnote_Symbol', 'Data_Value_Footnote',
       'Low_Confidence_Limit', 'High_Confidence_Limit', 'TotalPopulation',
       'TotalPop18plus', 'LocationID', 'CategoryID', 'MeasureId',
       'DataValueTypeID', 'Short_Question_Text', 'Geolocation'],
      dtype='object')

In [41]:
places["Measure"].value_counts()

Measure
Short sleep duration among adults                                                       6290
Visited dentist or dental clinic in the past year among adults                          6290
Mammography use among women aged 50-74 years                                            6290
All teeth lost among adults aged >=65 years                                             6290
Colorectal cancer screening among adults aged 45–75 years                               6290
Current lack of health insurance among adults aged 18-64 years                          5916
Cognitive disability among adults                                                       5916
Cancer (non-skin) or melanoma among adults                                              5916
Fair or poor self-rated health status among adults                                      5916
No leisure-time physical activity among adults                                          5916
Current cigarette smoking among adults                                                  5916
Taking medicine to control high blood pressure among adults with high blood pressure    5916
Visits to doctor for routine checkup within the past year among adults                  5916
Cholesterol screening among adults                                                      5916
Current asthma among adults                                                             5916
Independent living disability among adults                                              5916
Chronic obstructive pulmonary disease among adults                                      5916
Arthritis among adults                                                                  5916
Frequent physical distress among adults                                                 5916
Binge drinking among adults                                                             5916
Stroke among adults                                                                     5916
Any disability among adults                                                             5916
Obesity among adults                                                                    5916
Diagnosed diabetes among adults                                                         5916
Depression among adults                                                                 5916
High cholesterol among adults who have ever been screened                               5916
Hearing disability among adults                                                         5916
High blood pressure among adults                                                        5916
Vision disability among adults                                                          5916
Mobility disability among adults                                                        5916
Self-care disability among adults                                                       5916
Frequent mental distress among adults                                                   5916
Coronary heart disease among adults                                                     5916
Food insecurity in the past 12 months among adults                                      4600
Utility services shut-off threat in the past 12 months among adults                     4600
Housing insecurity in the past 12 months among adults                                   4600
Lack of reliable transportation in the past 12 months among adults                      4600
Lack of social and emotional support among adults                                       4600
Loneliness among adults                                                                 4600
Received food stamps in the past 12 months among adults                                 4600
Name: count, dtype: int64

In [42]:
places.head()

,Year,StateAbbr,StateDesc,LocationName,DataSource,Category,Measure,Data_Value_Unit,Data_Value_Type,Data_Value,...,Low_Confidence_Limit,High_Confidence_Limit,TotalPopulation,TotalPop18plus,LocationID,CategoryID,MeasureId,DataValueTypeID,Short_Question_Text,Geolocation
0,2023,AR,Arkansas,Drew,BRFSS,Health Outcomes,Arthritis among adults,%,Crude prevalence,29.9,...,26.6,33.3,16945,13230,05043,HLTHOUT,ARTHRITIS,CrdPrv,Arthritis,POINT (-91.7196579038053 33.5894113647675)
1,2023,AR,Arkansas,Fulton,BRFSS,Health Outcomes,Current asthma among adults,%,Crude prevalence,10.6,...,9.2,11.9,12421,9795,05049,HLTHOUT,CASTHMA,CrdPrv,Current Asthma,POINT (-91.817888079321 36.3816206347765)
2,2023,AR,Arkansas,Howard,BRFSS,Health Outcomes,Arthritis among adults,%,Crude prevalence,31.2,...,27.7,34.8,12533,9311,05061,HLTHOUT,ARTHRITIS,CrdPrv,Arthritis,POINT (-93.9938053308515 34.0889044688856)
3,2023,AR,Arkansas,Miller,BRFSS,Health Outcomes,Stroke among adults,%,Crude prevalence,4.7,...,4.2,5.3,42415,32396,05091,HLTHOUT,STROKE,CrdPrv,Stroke,POINT (-93.8924281761086 33.3123156126392)
4,2023,AR,Arkansas,Ouachita,BRFSS,Disability,Any disability among adults,%,Crude prevalence,42.8,...,37.9,47.8,21793,16948,05103,DISABLT,DISABILITY,CrdPrv,Any Disability,POINT (-92.882040791321 33.593253927504)

In [43]:
respiratory_places = places[
    places["Measure"].isin([
        "Current asthma among adults",
        "Chronic obstructive pulmonary disease among adults"
    ])
].copy()

respiratory_places["Measure"].value_counts()

Measure
Current asthma among adults                           5916
Chronic obstructive pulmonary disease among adults    5916
Name: count, dtype: int64

In [44]:
places_clean = respiratory_places[
    [
        "Year",
        "StateAbbr",
        "StateDesc",
        "LocationName",
        "LocationID",
        "TotalPopulation",
        "Measure",
        "Data_Value_Unit",
        "Data_Value_Type",
        "Data_Value",
        "Low_Confidence_Limit",
        "High_Confidence_Limit"
    ]
].copy()

places_clean = places_clean.rename(columns={
    "LocationID": "county_fips",
    "LocationName": "County Name",
    "StateDesc": "State Name"
})

places_clean.head()

,Year,StateAbbr,State Name,County Name,county_fips,TotalPopulation,Measure,Data_Value_Unit,Data_Value_Type,Data_Value,Low_Confidence_Limit,High_Confidence_Limit
1,2023,AR,Arkansas,Fulton,05049,12421,Current asthma among adults,%,Crude prevalence,10.6,9.2,11.9
9,2023,CO,Colorado,Lake,08065,7365,Current asthma among adults,%,Crude prevalence,10.2,9.0,11.6
64,2023,ME,Maine,Hancock,23009,56526,Current asthma among adults,%,Crude prevalence,12.1,10.7,13.5
66,2023,MD,Maryland,Carroll,24013,176639,Current asthma among adults,%,Crude prevalence,10.1,8.9,11.4
83,2023,NE,Nebraska,Thomas,31171,677,Current asthma among adults,%,Crude prevalence,9.0,7.9,10.1

In [45]:
places_clean.shape

(11832, 12)

In [46]:
places_clean.isna().sum()

Year                     0
StateAbbr                0
State Name               0
County Name              4
county_fips              0
TotalPopulation          0
Measure                  0
Data_Value_Unit          0
Data_Value_Type          0
Data_Value               4
Low_Confidence_Limit     4
High_Confidence_Limit    4
dtype: int64

In [47]:
places_clean[["Data_Value", "Low_Confidence_Limit", "High_Confidence_Limit", "TotalPopulation"]].describe()

,Data_Value,Low_Confidence_Limit,High_Confidence_Limit,TotalPopulation
count,11828.000000,11828.000000,11828.000000,1.183200e+04
mean,9.194707,7.925812,10.577697,2.205348e+05
std,2.115438,1.966977,2.284018,6.164536e+06
min,3.200000,2.600000,3.900000,4.300000e+01
25%,7.500000,6.300000,8.900000,1.047900e+04
50%,9.800000,8.500000,11.200000,2.579950e+04
75%,10.800000,9.400000,12.200000,6.946000e+04
max,17.600000,15.000000,20.600000,3.349149e+08

In [48]:
places_clean.sort_values("Data_Value").head()

,Year,StateAbbr,State Name,County Name,county_fips,TotalPopulation,Measure,Data_Value_Unit,Data_Value_Type,Data_Value,Low_Confidence_Limit,High_Confidence_Limit
213523,2023,VA,Virginia,Arlington,51013,234162,Chronic obstructive pulmonary disease among ad...,%,Crude prevalence,3.2,2.6,4.0
140908,2023,NM,New Mexico,Los Alamos,35028,19444,Chronic obstructive pulmonary disease among ad...,%,Age-adjusted prevalence,3.2,2.6,3.9
203570,2023,VA,Virginia,Falls Church,51610,14685,Chronic obstructive pulmonary disease among ad...,%,Age-adjusted prevalence,3.2,2.6,3.9
32900,2023,CA,California,Santa Clara,06085,1877592,Chronic obstructive pulmonary disease among ad...,%,Age-adjusted prevalence,3.3,2.7,3.9
227908,2023,WA,Washington,King,53033,2271380,Chronic obstructive pulmonary disease among ad...,%,Age-adjusted prevalence,3.3,2.8,4.0

In [49]:
places_clean.sort_values("Data_Value", ascending=False).head()

,Year,StateAbbr,State Name,County Name,county_fips,TotalPopulation,Measure,Data_Value_Unit,Data_Value_Type,Data_Value,Low_Confidence_Limit,High_Confidence_Limit
190679,2023,TN,Tennessee,Hancock,47067,6956,Chronic obstructive pulmonary disease among ad...,%,Crude prevalence,17.6,15.0,20.6
223551,2023,WV,West Virginia,McDowell,54047,17439,Chronic obstructive pulmonary disease among ad...,%,Crude prevalence,16.5,14.3,18.9
221026,2023,WV,West Virginia,Calhoun,54013,5959,Chronic obstructive pulmonary disease among ad...,%,Crude prevalence,16.2,13.8,18.8
221618,2023,WV,West Virginia,Mingo,54059,22023,Chronic obstructive pulmonary disease among ad...,%,Crude prevalence,16.1,13.8,18.9
122047,2023,MO,Missouri,Hickory,29085,8718,Chronic obstructive pulmonary disease among ad...,%,Crude prevalence,16.0,13.6,18.7

In [50]:
os.makedirs("data/01-interim", exist_ok=True)

places_clean.to_csv(
    "data/01-interim/cdc_places_respiratory_2025.csv",
    index=False
)

## Ethics

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Team Expectations

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Project Timeline Proposal

Instructions: Replace this with your timeline.  **PLEASE UPDATE your Timeline!** No battle plan survives contact with the enemy, so make sure we understand how your plans have changed.  Also if you have lost points on the previous checkpoint fix them